### ISSUE TITLE
Trying to get email sent from dedicated server

### ISSUE THREAD

**Issue by febrez** [Phyks/Emails_SMS_Free_Mobile_API#3]
I have this error when I try to fetch a mail, here is detailed log : 

```
Connecting to imap.****.com… Connected
Logging as ***@****.com… Logged in
# /opt/python3.3/lib/python3.3/encodings/__pycache__/ascii.cpython-33.pyc matches /opt/python3.3/lib/python3.3/encodings/ascii.py
# code object from /opt/python3.3/lib/python3.3/encodings/__pycache__/ascii.cpython-33.pyc
import 'encodings.ascii' # <_frozen_importlib.SourceFileLoader object at 0x7f9ec2840210>
Traceback (most recent call last):
  File "emails_sms_free.py", line 154, in <module>
    hashlib.md5((imap_server['server']+imap_server['login']).encode('utf-8')).hexdigest()))
  File "emails_sms_free.py", line 109, in get_emails
    text = part.get_payload(decode=True).decode(str(charset))
LookupError: unknown encoding:
# clear builtins._
(...)
```

**Comment by Phyks** [comment]
Did you really get such weird formatted emails in real life? I am not sure it is even a valid header :/

Still, that could be solved quite easily.

**Comment by febrez** [comment]
To get it works I removed

`.decode(str(charset))` in line 109

But now the content of other emails displays unwanted characters

**Comment by Phyks** [comment]
Could you try https://github.com/Phyks/Emails_SMS_Free_Mobile_API/pull/4 ?

**Comment by febrez** [comment]
```
charset = part.get_content_charset()
if not charset:
```

That works. Could we force a charset when none specified ? 

Thank you for help and this usefull script

**Comment by Phyks** [comment]
Actually, not easily. At the moment, it just returns a byte string, that may be utf-8 encoded or anything else. We cannot make any safe assumption on this I think.

This is a really weird case, I have never seen such emails before.
